site_name: "FastForward"
site_description: "FastForward: Neural Network Quantization"
site_url: !ENV DOCS_SITE_URL
repo_url: !ENV DOCS_REPO_URL
site_dir: "site"
watch: [mkdocs.yml, README.md]
edit_uri: edit/main/docs/
strict: true

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  name: material
  logo: assets/ff-logo-white.png
  favicon: assets/ff-logo-purple.png
  palette:
    primary: deep purple
  features:
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.tabs
  - toc.follow
  # - toc.integrate # enable page-level TOC in the left-hand navigation sidebar


nav:
  - Home: index.md
  - Tutorials: examples/index.md
  - API reference: reference/

exclude_docs: |
  gen_reference.py
  no_sitemap_plugin.py
  source_link_hook.py
  notebook_meta_hook.py

not_in_nav: |
  examples/**/*.nb.py
  examples/autoquant.md

# Customization
extra:
  version:
    provider: mike

plugins:
  # https://github.com/danielfrg/mkdocs-jupyter
  - mkdocs-jupyter:
      execute: True
      include: ["*.nb.py"]
      include_source: True
      allow_errors: false
      cache_dir: !ENV [MKDOCS_JUPYTER_CACHE_DIR, ".mkdocs_cache/mkdocs-jupyter"] #, ".cache/mkdocs-jupyter"]

  # https://squidfunk.github.io/mkdocs-material/plugins/search/
  - search
  # https://github.com/oprypin/mkdocs-gen-files
  # Generate files for Reference API dynamically
  - gen-files:
      scripts:
        - docs/hooks/gen_reference.py
  # https://github.com/oprypin/mkdocs-literate-nav
  - literate-nav:
      nav_file: summary.md
  - mkdocstrings:
      custom_templates: docs/_templates
      handlers:
        python:
          paths: [src/fastforward]
          options:
            heading_level: 3
            show_source: true
            show_inheritance_diagram: True
            show_if_no_docstring: True
            merge_init_into_class: true
            allow_inspection: true
            show_root_full_path: true
            show_root_members_full_path: true
            show_symbol_type_heading: true
            show_root_toc_entry: false
            group_by_category: true
            show_category_heading: true
            filters:
              - "!^_"
  - section-index
  # https://github.com/jimporter/mike
  # Generate doc for each version
  - mike:
      version_selector: True

hooks:
  - docs/hooks/no_sitemap_hook.py
  - docs/hooks/source_link_hook.py
  - docs/hooks/notebook_meta_hook.py

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.snippets:
      base_path: [!relative $config_dir]
      check_paths: true
  - toc:
      permalink: "#"
      toc_depth: 4

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/clickable-cards.js
  - javascripts/api-heading-styling.js