name: Feature Request
description: File a feature request.
title: "[Feature]: "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: textarea
    id: description
    attributes:
      label: What feature would you like to see in FastForward?
      description: A clear and concise description of the feature.
      placeholder: FastForward should ...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this feature important to you?
      description: Explain how this feature will help you or others.
      placeholder: This feature will help me/us to ...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How would you prioritize this feature?
      options:
        - Must Have - Now
        - Must Have - Soon
        - Should Have - Now
        - Should Have - Soon
        - Nice To Have - Now
        - Nice To Have - Soon
      description: Help us understand the importance and urgency of this feature.
    validations:
      required: true

  - type: textarea
    id: related_issues_list
    attributes:
      label: List related issue numbers (if any)
      description: Separate issue numbers with commas.
      placeholder: "#123, #456"
