ARG VER_PYTHON
FROM python:${VER_PYTHON}

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ARG VER_TORCH \
    VER_CUDA

RUN --mount=type=bind,rw,target=/docker-ctx export CUDA_VERSION_NO_DOT=$(echo "${VER_CUDA}" | tr -d .) && uv pip install --system --extra-index-url https://download.pytorch.org/whl/cu${CUDA_VERSION_NO_DOT} --no-cache torch==${VER_TORCH} /docker-ctx --group /docker-ctx/pyproject.toml:test && uv pip uninstall --system fastforward
CMD ["/bin/bash"]
