#!/usr/bin/env bash
export UV_PROJECT_ENVIRONMENT="${UV_PROJECT_ENVIRONMENT:-/opt/venv}"
uv sync --inexact --no-default-groups --group dev --group test --group test-regression --group docs --project "${1:-.}"
