name: Generate docs

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
      - opened
      - reopened
      - synchronize
    branches:
      - main

env:
  PAGES_BRANCH: "pages"
  PAGES_PREFIX: public
  HF_HUB_OFFLINE: ${{ vars.HF_HUB_OFFLINE }}
  HF_HUB_CACHE: ${{ vars.HF_HUB_CACHE }}
  HF_DATASETS_CACHE: ${{ vars.HF_DATASETS_CACHE }}

concurrency:
  group: ${{ github.workflow }}

jobs:
  docs:
    if: github.server_url != 'https://github.com' && github.event.pull_request.state != 'closed'
    runs-on: k8s-gpu
    container:
      image: python:3.12
    steps:
      - name: Checkout the "$PAGES_BRANCH" branch
        uses: actions/checkout@v4
        with:
          ref: "${{ env.PAGES_BRANCH }}"

      - uses: actions/checkout@v4

      - run: |
          apt update -qq && apt install -y jq rsync

      - name: Generate docs
        run: |
          export DOCS_REPO_URL="${{ github.server_url }}/${{ github.repository }}"
          export DOCS_SITE_URL="$(curl -k -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/pages | jq -r '.html_url')"
          python3 -m pip install ".[docs]"
          git config --global --add safe.directory '*'
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          export PYTHONPATH="$PYTHONPATH:$PWD/docs/examples/quick_start"
          DOCS_VERSION=''
          if [ "${{ github.event_name }}" = "push" ] ; then
            DOCS_VERSION="$DOCS_VERSION ${{ github.ref_name }}"
          fi
          if [ "${{ github.event_name }}" = "pull_request" ] ; then
            DOCS_VERSION="$DOCS_VERSION $(echo '${{ github.head_ref }}' | sed 's/^docs\///')"
          fi
          if [ "${{ github.ref_type }}" = "tag" ] ; then
            DOCS_VERSION="$DOCS_VERSION latest"
          fi
          mike deploy --config-file mkdocs.yml --update-aliases --deploy-prefix $PAGES_PREFIX --branch $PAGES_BRANCH $DOCS_VERSION

      - name: Save changes docs
        if: github.ref_name == 'main' || startsWith(github.head_ref, 'docs/')
        run: |
          git push origin $PAGES_BRANCH:$PAGES_BRANCH

  deploy:
    if: github.server_url != 'https://github.com' && github.event.pull_request.state != 'closed' && (github.ref_name == 'main' || startsWith(github.head_ref, 'docs/'))
    runs-on: ubunut-latest
    needs: docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ env.PAGES_BRANCH }}"
      - uses: actions/upload-pages-artifact@v2
        with:
          path: "${{ env.PAGES_PREFIX }}"
      - uses: actions/deploy-pages@v3
        id: deployment

      - name: Deploy public docs
        if: github.ref_name == 'main'
        run: |
          git clean -xdf
          git fetch --force
          git switch gh-pages
          git checkout $PAGES_BRANCH -- $PAGES_PREFIX
          rsync -av $PAGES_PREFIX/index.html $PAGES_PREFIX/../index.html
          find $PAGES_PREFIX -maxdepth 1 -type d  -name 'main' -o -name 'latest' -o -regex '.*/[0-9]+.[0-9]+.[0-9]+' | xargs -i -n 1 sh -c 'rsync -av {} $(readlink -f {}) $PAGES_PREFIX/..'
          jq --arg versions "$(find $PAGES_PREFIX/.. -mindepth 1 -maxdepth 1 -type d -printf '%f ')" '[.[] | select(.version | IN($versions | split(" ") | .[]))]' $PAGES_PREFIX/versions.json > $PAGES_PREFIX/../versions.json
          rm -rf $PAGES_PREFIX
          grep -rl "https://github\..*/fastforward" --exclude-dir=.git . | xargs sed -i 's|https://github\..*/fastforward|https://github.com/Qualcomm-AI-research/fastforward|g'
          git add --all .
          if [ -n "$(git status --porcelain)" ] ; then
            git status
            git commit --reuse-message=$PAGES_BRANCH
            git push origin gh-pages:gh-pages
          fi

  cleanup:
    if: github.server_url != 'https://github.com' && github.event.pull_request.state == 'closed' && startsWith(github.head_ref, 'docs/')
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ env.PAGES_BRANCH }}"
      - uses: actions/checkout@v4
      - run: |
          python3 -m pip install ".[docs]"
          git config --global --add safe.directory '*'
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mike delete --push --deploy-prefix $PAGES_PREFIX --branch $PAGES_BRANCH $( echo "${{ github.head_ref }}" | sed 's/^docs\///' )
          git switch $PAGES_BRANCH
      - uses: actions/upload-pages-artifact@v2
        with:
          path: "${{ env.PAGES_PREFIX }}"
      - uses: actions/deploy-pages@v3
        id: deployment
