name: Generate docs

on:
  pull_request:
    types:
      - closed
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - "docs/**"
env:
  PAGES_BRANCH: "pages"
  PAGES_PREFIX: public
  HF_HUB_OFFLINE: ${{ vars.HF_HUB_OFFLINE }}
  HF_HUB_CACHE: ${{ vars.HF_HUB_CACHE }}
  HF_DATASETS_CACHE: ${{ vars.HF_DATASETS_CACHE }}

jobs:
  docs:
    if: github.server_url != 'https://github.com' && github.event.pull_request.state != 'closed'
    runs-on: k8s-gpu
    container:
      image: python:3.12
    steps:
      - name: Checkout the "$PAGES_BRANCH" branch
        uses: actions/checkout@v4
        with:
          ref: "${{ env.PAGES_BRANCH }}"
      - uses: actions/checkout@v4
      - run: curl -L https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64 -o jq && chmod +x ./jq
      - name: Generate docs
        run: |
          export DOCS_REPO_URL="${{ github.server_url }}/${{ github.repository }}"
          export DOCS_SITE_URL="$(curl -k -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/pages | ./jq -r '.html_url')"
          python3 -m pip install ".[docs]"
          git config --global --add safe.directory '*'
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          export PYTHONPATH="$PYTHONPATH:$PWD/docs/examples/quick_start"
          mike deploy --push --config-file mkdocs.yml --update-aliases --deploy-prefix $PAGES_PREFIX --branch $PAGES_BRANCH $( echo "${{ github.event.pull_request.head.ref }}" | sed 's/^docs\///' ) $([ \"${{ github.ref_type }}\" = \"tag\" ] && echo "latest")
          mike set-default --push --deploy-prefix $PAGES_PREFIX --branch $PAGES_BRANCH latest
          git switch $PAGES_BRANCH
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v2
        with:
          path: "${{ env.PAGES_PREFIX }}"

  deploy:
    if: github.server_url != 'https://github.com' && github.event.pull_request.state != 'closed'
    runs-on: ubuntu-latest
    needs: docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3

  cleanup:
    if: github.server_url != 'https://github.com' && github.event.pull_request.state == 'closed' && github.ref_name != github.event.repository.default_branch
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ env.PAGES_BRANCH }}"
      - uses: actions/checkout@v4
      - run: |
          python3 -m pip install ".[docs]"
          git config --global --add safe.directory '*'
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mike delete --deploy-prefix $PAGES_PREFIX --branch $PAGES_BRANCH --push $( echo "${{ github.event.pull_request.head.ref }}" | sed 's/^docs\///' )
          git switch $PAGES_BRANCH
      - uses: actions/upload-pages-artifact@v2
        with:
          path: "${{ env.PAGES_PREFIX }}"
      - uses: actions/deploy-pages@v3
        id: deployment
