name: PR Lint

on:
  pull_request:
     types: [edited]

jobs:
  pr_content_lint:
    if: github.server_url != 'https://github.com'
    name: Verify PR content
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint the contents of the PR
        shell:
          bash # enables `-o pipefail`
        run: |
          echo "${{ github.event.pull_request.body }}" | python3 scripts/pr_content_lint.py
